# -*- coding: utf-8 -*-
"""Sprint 2 - PAAI

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yMkclFUqDPBvWo-sErXi_jHjZ5TCLwOk
"""

!pip install -q google-generativeai

from google.colab import userdata
import google.generativeai as genai

API_KEY = userdata.get("GEMINI_API_KEY")

genai.configure(api_key=API_KEY)

print("Conectado com sucesso!")

model = genai.GenerativeModel("gemini-2.5-flash")

response = model.generate_content("Olá")

print(response.text)

import google.generativeai as genai

SYSTEM_PROMPT = """
Você é o ChargeGrid Assistant, assistente da GoodWe para o EV Challenge 2026.

Você ajuda motoristas de veículos elétricos.

Suas funções:

- Explicar como iniciar carregamentos
- Informar progresso da recarga
- Explicar tarifação dinâmica
- Explicar pagamentos PIX, crédito e débito
- Auxiliar no encerramento da sessão
- Encaminhar problemas físicos ao suporte técnico

Regras:

- Responda sempre em português.
- Seja educado e acolhedor.
- Nunca invente dados.
- Máximo de 3 parágrafos curtos.
"""

SESSION_DATA = """
Dados da sessão atual:

Bateria: 67%
Energia consumida: 18.4 kWh
Valor acumulado: R$22,10
Tempo restante: 23 minutos
"""

historico = []

model = genai.GenerativeModel("gemini-2.5-flash")

def conversar(pergunta):

    prompt = f"""
{SYSTEM_PROMPT}

{SESSION_DATA}

Histórico:
{historico}

Usuário:
{pergunta}
"""

    resposta = model.generate_content(prompt)

    historico.append(f"Usuário: {pergunta}")
    historico.append(f"Assistente: {resposta.text}")

    print("\nChargeGrid Assistant:")
    print(resposta.text)

conversar("Como eu começo a carregar meu carro aqui?")

conversar("Quanto tempo ainda falta para terminar minha recarga?")

conversar("O cabo não está encaixando no meu carro")